### ISSUE TITLE
Support streaming gzip encoding?

### ISSUE THREAD

**Issue by mmmries** [benhaney/Jsonrs#14]
I am loving the approach of your library. At my day job I have a use-case where we create some very large data structures and encode them to JSON, then gzip that JSON. It is pretty common for us to see JSON documents that are 140MB+ in size which get compressed to ~9MB after gzipping.

Would you be open to me extending your library to support an option to do a streaming gzip encoding of the JSON as it's being compiled. This would reduce my system's memory footprint significantly since I wouldn't need to hold the 140MB of JSON in memory. I would only need to hold 9MB of gzipped json.

**Comment by benhaney** [comment]
I'd be very open to that, yeah. Can you talk a little more about how you intend to implement it?

**Comment by mmmries** [comment]
I don't have a plan for how to implement yet. I first wanted to check if you were open to supporting this in your library before I spent a bunch of time. I have only a little background in rust (I wrote [bayesic_nif](https://hex.pm/packages/bayesic_nif) to learn rust and rustler), so I'm not sure if gzip encoding is a concept that exists within the serde community, but I plan to start there and see what I can find.

**Comment by benhaney** [comment]
I'm definitely open to supporting it - it sounds like a great and fitting feature. And yeah, I'm not aware of anything like a serde_gzip, so you'll probably need to do quite a bit of plumbing to get this working without allocating the entire uncompressed json string at once.
