### ISSUE TITLE
Unusable with Phoenix Sockets

### ISSUE THREAD

**Issue by jnylen** [benhaney/Jsonrs#6]
Hi @benhaney,
We are having some issues using this with phoenix live dashboard as it's making the views crash.

I set up the project like this:

```
# config.exs
config :phoenix, :json_library, Jsonrs
```

And then you go to `/dashboard` after setting it up and you'll see the loading bar just continue loading.

To debug the issues you'll have to create a module with cloning it and adding `Jason` as a dependency:
```
defmodule TestApp.Jsontest do
  def decode!(input, opts \\ []) do
    IO.puts("####### decode")
    IO.puts("INC VAL:")
    IO.inspect(input)

    IO.puts("JASON:")
    IO.inspect(Jason.decode!(input, opts))
    IO.puts("JSONRS:")
    IO.inspect(Jsonrs.decode!(input, opts))
    IO.puts("####### decode")

    Jsonrs.decode!(input, opts)
  end

  def encode_to_iodata!(input, opts \\ []) do
    IO.puts("####### ENCODE")
    IO.puts("INC VAL:")
    IO.inspect(input)

    IO.puts("JASON:")
    IO.inspect(Jason.encode!(input, opts))
    IO.puts("JSONRS:")
    IO.inspect(Jsonrs.encode!(input, opts))
    IO.puts("####### ENCODE")

    Jsonrs.encode!(input, opts)
  end
end
```

And pointing the json_library above to it.

Then you'll see some differences between Jason and Jsonrs:

```
####### ENCODE
INC VAL:
[nil, "26", "phoenix", "phx_reply", %{response: %{}, status: :ok}]
JASON:
"[null,\"26\",\"phoenix\",\"phx_reply\",{\"response\":{},\"status\":\"ok\"}]"
JSONRS:
"[null,\"26\",\"phoenix\",\"phx_reply\",{\"response\":{},\"status\":\"Ok\"}]"
####### ENCODE
```

It seems like `Jsonrs` is turning atoms into capitalized letters which is breaking stuff here and there.

**Comment by benhaney** [comment]
>It seems like `Jsonrs` is turning atoms into capitalized letters

Apparently only `:ok` (`"Ok"`) and `:error` (`"Err"`) are affected by this, and it seems to be [a quirk of `serde_rustler`](https://github.com/sunny-g/serde_rustler/blob/283e41ba3d563767ddc6f328231e6c077ca97a4c/serde_rustler/src/atoms.rs#L52-L55) treating those specially, so I guess I'll update my fork to change that behavior.

Thanks for the report! I'll publish a new patch version of Jsonrs in a bit that uses the updated dependency once I've tested it.

**Comment by benhaney** [comment]
@jnylen Let me know if 0.1.6 works better for you

**Comment by jnylen** [comment]
@benhaney can confirm it works!

Thanks for the fast fix!
